### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by b1n4ryj4n** [bashkirtsevich/grapefruit-crawler#1]
hey if i try to start your app my console says:

`Traceback (most recent call last):
  File "C:\grapefruit-crawler\app.py", line 7, in <module>
    import motor.motor_asyncio
  File "C:\Python370\lib\site-packages\motor\motor_asyncio.py", line 20, in <module>
    from .frameworks import asyncio as asyncio_framework
  File "C:\Python370\lib\site-packages\motor\frameworks\asyncio\__init__.py", line 31
    from asyncio import async as ensure_future
                            ^
SyntaxError: invalid syntax`

i installed all requirements with mongodb 4.0 using Python 3.7.0 at Win 10.

**Comment by bashkirtsevich** [comment]
Is `motor==1.1` and `pymongo==3.5.1` compatible with `python3.7`?

**Comment by b1n4ryj4n** [comment]
i upgraded to pymongo-3.7.1 and motor-2.0.0 now it seems to work, thanks. But now comes a new error: `ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<DHTCrawler.handle_message() done, defined at C:\grapefruit-crawler\crawler.py:154> exception=TypeError("MotorCollection object is not callable. If you meant to call the 'torrents.count' method on a MotorCollection object it is failing because no such method exists.")>
Traceback (most recent call last):
  File "C:\grapefruit-crawler\crawler.py", line 161, in handle_message
    await self.handle_query(msg, addr)
  File "C:\grapefruit-crawler\crawler.py", line 236, in handle_query
    await self.get_peers_received(node_id, info_hash, addr)
  File "app.py", line 114, in get_peers_received
    await self.enqueue_torrent(info_hash)
  File "app.py", line 108, in enqueue_torrent
    has_torrent = await self.is_torrent_exists(info_hash)
  File "app.py", line 40, in is_torrent_exists
    result = await self.db.torrents.count(filter={"info_hash": hexlify(info_hash)}) > 0
  File "C:\Python370\lib\site-packages\motor\core.py", line 554, in __call__
    self.delegate.name)
TypeError: MotorCollection object is not callable. If you meant to call the 'torrents.count' method on a MotorCollection object it is failing because no such method exists.`

Edit: installed it now on centos 7 with docker and all works fine :D

**Comment by bashkirtsevich** [comment]
On a windows 10 with requirements from `requirements.txt` (`python 3.6.3`) all works fine. Same configuration in docker image.

Any other questions or problems? Close this issue?
